### ISSUE TITLE
CC API update

### ISSUE THREAD

**Issue by Towsty** [CD4017BE/CD4017BE_lib#1]
Any chance you could update the version of the ComputerCraft API your mod uses? It seems to cause crashes when using turtles with the latest (and last I believe) version of CC for 1.7.10. 

See this post on CC forum:
http://www.computercraft.info/forums2/index.php?/topic/25598-any-turtle-use-crashing/

Also see dan200s comment:
http://www.computercraft.info/forums2/index.php?/topic/25598-any-turtle-use-crashing/page__view__findpost__p__242693

**Comment by CD4017BE** [comment]
Fixed, and also shouldn't cause trouble anymore on future Computercraft-API changes.
