### ISSUE TITLE
About 10-15 minutes to deallocate all objects in a old PC!

### ISSUE THREAD

**Issue by z3nth10n** [CD4017BE/CD4017BE_lib#11]
Hi, I'm using Forge and SpongeForge and well... My old computer:

Intel Core 2 Duo E7500
4GB RAM
Debian 9 (virtualizated, I will explain it later)

And:

Minecraft : 1.10.2
SpongeAPI : 5.2.0-SNAPSHOT-c675e80
SpongeForge : 1.10.2-2281-5.2.0-BETA-2464
Minecraft Forge : 12.18.3.2422     

Gets freezed when [FMLServerAboutToStartEvent](https://github.com/CD4017BE/CD4017BE_lib/blob/5b3abe3f7e449f4d7c84297d430cdfca044a989d/src/java/cd4017be/lib/Lib.java#L61) gets called.

[03:23:51] [Server thread/TRACE] [CD4017BE_lib/CD4017BE_lib]: Sending event FMLServerAboutToStartEvent to mod CD4017BE_lib
[03:38:01] [Server thread/TRACE] [CD4017BE_lib/CD4017BE_lib]: Sent event FMLServerAboutToStartEvent to mod CD4017BE_lib

As you can see, it has lasted about 15 minutes to do "nothing". I have to say also, that, I'm using a virtualization system with Debian 9 and inside I'm running the server.

Anyway, I have a newer computer:

Intel i7-6700k
16GB RAM

And this process lasts about two seconds only, so, I don't know what is wrong here.

Thanks!

**Comment by CD4017BE** [comment]
The only things the mod is doing during FMLServerAboutToStartEvent is:
- setting the static reference to the recipe script loader to null.
- setting the static reference to a 64kB Bytebuffer to null.
- calling the Java garbage collector to clean up both from RAM as well as all the other memory trash that is typically produced during launch (by minecraft itself, other mods, forge, sponge etc.)

So it's probably the garbage collector, but that also means without this, you probably would have gotten that 15min lag later in game instead as soon as the RAM runs out.

I checked the logs from my own test launches (MinecraftForge, cd4017be_lib, InductiveAutomation, JEI and Tesla installed) and there it takes less than a second:
> [21:03:27] [Server thread/TRACE] [CD4017BE_lib/CD4017BE_lib]: Sending event FMLServerAboutToStartEvent to mod CD4017BE_lib
> [21:03:28] [Server thread/TRACE] [CD4017BE_lib/CD4017BE_lib]: Sent event FMLServerAboutToStartEvent to mod CD4017BE_lib
> [21:03:28] [Server thread/DEBUG] [FML/]: Bar Step: ServerAboutToStart - CD4017BE_lib took 0,634s

**Comment by z3nth10n** [comment]
Yes, I know that if the System.gc is not called I will run out my memory later. But is totally neccesary at this point, is suppose that the gc is cleaned in other place for sure. Maybe, deleting this line of code, I get something different but this is so weird that call this method causes a freeze of the main thread for about 10-15 minutes in old spec PC.

If you want to see my modpack:

https://www.technicpack.net/modpack/hugecraft-tech-much-more.1070846

**Comment by CD4017BE** [comment]
I removed the garbage collector call:
(https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v4.4.4)
But this will probably only slightly reduce the loading time of your modpack and not completely fix your problem that it overall takes about 10x longer to load on your low PC. 

It's probably that 4GB RAM is a bit too low to fluently load that huge pack and that garbage collection seems to be very slow on your virtualized environment and/or processor.
