### ISSUE TITLE
Is there a way to to bit-wise shift operations?

### ISSUE THREAD

**Issue by Kalin-Rudnicki** [CD4017BE/CD4017BE_lib#23]

**Comment by CD4017BE** [comment]
Maybe there is, maybe not, it depends on which mod and features you're talking about:
- Bit shift operations in the `configuration file scripting language` my mods are using for crafting recipes, other configuration and to define some block models? -> No, there are no operators for that you need to use multiplication and division instead.
- Bit shift operations in `Automated Redstone` (the predecessor mod to Redstone Control wich is no longer actively developed)? -> Yes, there is both a dedicated block and an operator inside the circuit designer for that.
- Bit shift operations in `Redstone Control` (I'm guessing you meant this but then you should have posted this in the **Redstone Control** repository, not **CD4017BE_lib**) -> Yes, there is an operator for that in the circuit designer in the `Bits and Bytes` tab, but no dedicated block.
