### ISSUE TITLE
Crash when converting directionally-oriented blocks to Microblocks

### ISSUE THREAD

**Issue by gamrguy** [CD4017BE/CD4017BE_lib#24]
In `MicroBlockItem.convert()`, there is a null `PlayerEntity` sent into a `BlockItemUseContext`. While this is annotated as `@Nullable` in the Mojang mappings, this is actually incorrect: two methods in that class use `Direction.orderedByNearest()` without a null check, which requires the `PlayerEntity` not be null.

This causes blocks which attempt to use `BlockItemUseContext.getNearestLookingDirection()` to determine the block's orientation to crash the game with a `NullPointerException` when placed in the Microblock Workbench.

Examples include:
- Dispensers
- Droppers
- Observers
- Various modded directionally-oriented blocks

**Comment by CD4017BE** [comment]
Ok, so I probably have to give it a FakePlayer then.
