### ISSUE TITLE
Suggestion: blueprint system

### ISSUE THREAD

**Issue by NighthowlerStudios** [CD4017BE/CD4017BE_lib#25]
Tiny Redstone has its own blueprint system, but your mod could use one as well.  I'm not sure if Create's blueprint system works or not (using vanilla nbt structure files to pull it off) I'd have to check.

Maybe simply put, add support to export to nbt?

**Comment by CD4017BE** [comment]
It is currently possible to copy microblock structures in the Microblock Workbench.
So with blueprints, do you mean assembling microblock Structures from "share strings" ?

**Comment by CD4017BE** [comment]
Oh and with command blocks you can use `/data get` and `/data modify` to copy structures from one world to another. (Use the minecraft log to CTRL-C the data get output)

**Comment by NighthowlerStudios** [comment]
oh that's awesome!  you've literally thought of everything haha, I'm still kinda new to your mod but damn, that's actually what I was looking for

is there anywhere I can get in touch with you closer?  It would be nice to have a helping hand as I attempt to build a redstone "super"computer in my modpack

**Comment by CD4017BE** [comment]
I have a discord server: https://discord.gg/Z3MMuZDpSM
