### ISSUE TITLE
Texture stretching on microblocks with optifine shaders

### ISSUE THREAD

**Issue by Zoinkless** [CD4017BE/CD4017BE_lib#27]
Issues discovered with the textures of microblocks stretching over the entire block space with optifine internal shaders being used. Current version of CD4017BE lib is installed and Optifine version HD U G8 is being used. 

![2021-08-16_22 44 39](https://user-images.githubusercontent.com/89021725/129565758-46515788-9659-4849-812e-3f2cef57eee7.png)

**Comment by CD4017BE** [comment]
From the way the blocks are messed up, it looks like a vertex format mismatch (like XYZ-vertex coordinated being interpreted as texture UV, normals or whatever).

I did some testing and found out that, if you have shaders set to OFF microblocks are rendered correctly.
If you then switch to optifine internal shaders while still in game, only the microblocks are messed up that where placed, changed or got within view distance **after** enabling shaders. But the ones that still render based on cached vertex data from before enabling shaders are fine.

This means that the vertex data (BakedQuads) that my mod feeds to the render engine is correct and not cause of the issue. But my code is computing this vertex data on the fly based on models of other blocks fetched from minecraft's model cache, blindly assuming that they are in standard block vertex format (which is probably no longer true with Optifine shaders).

The obvious solution would be to just check if the models actually are in standard block model format and convert them if needed. But there is a problem:  
I can't find a way to do that! Minecraft's and Forge's API don't provide any way for my code to actually figure out what vertex format their model data (just an int array) is in. And it seems that internally they also just treat the data as standard block vertex format like I do. Why does Optifine even mess with that in the first place?
