### ISSUE TITLE
Request: Transparent Microblocks

### ISSUE THREAD

**Issue by kettle4boilin** [CD4017BE/CD4017BE_lib#28]
Hey,
is it possible to make it so blocks retain their transparency when turned into microblocks? Chisel and bits has this, but has many issues with Magnesium(and the other fabric optimization forge ports), so it's not ideal, and besides, I prefer the simplicity of this mod.

Transparent parts(like leaves) would look really cool imo! 

Additionally, can you introduce a way to turn microblocks back into ordinary blocks(if there isn't already)?

Thanks, and keep up the great work!

(P.S. I know this isn't an 'issue' but I couldn't find a suggestions page, feel free to redirect me if you want and I'll move my request there)

**Comment by CD4017BE** [comment]
I thought my mod would not allow transparent blocks to be turned into microblocks but I just checked it and apparently it does allow it, which results in various render glitches. I also just found out that foliage colored blocks like grass don't render correctly either. In other words: while looking into how transparent blocks could be supported I found a few existing bugs.

Converting microblocks back to regular blocks is already possible: If you put a regular block into the "replicate" slot of the Microblock Workbench, it will assemble it from Block Bits.

**Comment by kettle4boilin** [comment]
Thanks for the block tip!

In terms of transparency and foliage colors, does this mean you're not planning on it? Or might you consider adding them?

They would be very nice to have, but I couldn't blame you as this is a core mod, so it might not have much of a use for its original purpose.

Edit: Just saw you mentioned 'while looking into how transparent blocks could be supported', you can ignore this, I'm just an idiot, lol

**Comment by CD4017BE** [comment]
Just as a note: Foliage colored blocks parts are now rendered with their default foliage color (the one that's also used in items) because for location (biome) dependent foliage colors, client side world access for Microblock Parts is necessary. And this would require significant API changes for a relatively minor feature so I didn't do it.

**Comment by kettle4boilin** [comment]
Alright, that's fair, thanks!
