### ISSUE TITLE
this or automated redstone crashes Dedicated forge server 1.10.2 build 2088 on startup

### ISSUE THREAD

**Issue by kreezxil** [CD4017BE/CD4017BE_lib#5]
crash report:
https://gist.github.com/45af6b936c69671c21980aa5c37f1447

fml server latest:
https://gist.github.com/b58d00d3b46383ce731ef0c33cad13ab

**Comment by CD4017BE** [comment]
Some access to classes that are only available on clients wasn't separated enough from the initialization methods that are also called server side. Fix (for both mods):
[CD4017BE_lib](https://github.com/CD4017BE/CD4017BE_lib/releases/tag/v4.3.1)
[AutomatedRedstone](https://github.com/CD4017BE/AutomatedRedstone/releases/tag/v4.2.1)
