### ISSUE TITLE
Library Version Conflict

### ISSUE THREAD

**Issue by Tellik** [CD4017BE/CD4017BE_lib#9]
Quote from Automated Redstone: "It also works well as add-on mod for InductiveAutomation"

Issue: Inductive Automation requires Library version 4.3.4 and is unable to use the most recent/higher version library. Automated Redstone requires Library version 4.4.3. Since it's impossible to have both versions of the library at the same time, it's impossible to use both Automated Redstone with Inductive Automation unless Inductive Automation is updated to be able to use the most recent version of the library.

**Comment by CD4017BE** [comment]
The new version of Inductive Automation you're asking for already existed here on github all the time: [5.3.4](https://github.com/CD4017BE/InductiveAutomation/releases/tag/v5.3.4)

I just forgot to upload it at Curse too. Sorry for that.
Now It's also available [there](https://minecraft.curseforge.com/projects/inductive-automation/files/2419469).
